import card
import move

def initialize_moves(moves):
    newMove = move.Move(0, "slash", "40, 100%", "common", False)
    moves.append(newMove)
    newMove = move.Move(1, "block", "+1 def, 100%", "common", True)
    moves.append(newMove)
    newMove = move.Move(2, "counter", "reflect damage, 33%", "common", True)
    moves.append(newMove)
    newMove = move.Move(3, "barrier", "+1 spdef, 100%", "common", True)
    moves.append(newMove)

    newMove = move.Move(4, "blade dance", "+1 atk, 100%", "common", True)
    moves.append(newMove)
    newMove = move.Move(5, "focus", "+1 spatk, 100%", "common", True)
    moves.append(newMove)
    newMove = move.Move(6, "agility", "+1 spe, 100%", "common", True)
    moves.append(newMove)
    newMove = move.Move(7, "Aerial ace", "60, Never misses", "common", False)
    moves.append(newMove)
    newMove = move.Move(8, "Meteor prayer", "155, 70%. This move lowers the users atk and spatk", "common", True)
    moves.append(newMove)
    newMove = move.Move(9, "Pickup", "attempts to find a card", "common", True)
    moves.append(newMove)

    newMove = move.Move(10, "water cannon", "120, 80%", "rare", True)
    moves.append(newMove)
    newMove = move.Move(11, "fireslash", "95, 95%", "rare", False)
    moves.append(newMove)
    newMove = move.Move(12, "wood impale", "90, 90%. This move also heals the user a bit.", "rare", False)
    moves.append(newMove)
    newMove = move.Move(13, "dark pulse", "80, 100%. This move also may flinch the target", "rare", True)
    moves.append(newMove)
    newMove = move.Move(14, "gear grind", "50, 95%. This move will lower the spdef of the target", "rare", True)
    moves.append(newMove)
    newMove = move.Move(15, "flash fist", "60, 100%. This move usually goes first.", "rare", False)
    moves.append(newMove)

    newMove = move.Move(20, "moonblast", "180, 70%", "super rare", True)
    moves.append(newMove)
    newMove = move.Move(21, "spiked blindside", "90, 100%. This move make spikes dig into the target every turn.", "super rare", False)
    moves.append(newMove)
    newMove = move.Move(22, "theif", "50, 100%. This move steals a random item from the target", "super rare", False)
    moves.append(newMove)
    newMove = move.Move(23, "wind pulse", "70, 100%. +1 def", "super rare", True)
    moves.append(newMove)
    newMove = move.Move(24, "psyshock", "70, 100%. +1 spdef", "super rare", False)
    moves.append(newMove)

    newMove = move.Move(30, "lightspeed lash", "85, 100%. This move usually goes first", "legendary", False)
    moves.append(newMove)
    newMove = move.Move(31, "midnight cresent slash", "180, 60%.", "legendary", False)
    moves.append(newMove)
    newMove = move.Move(32, "eruption", "300, 100%. This moves damage is based off the users health.", "legendary", True)
    moves.append(newMove)
    newMove = move.Move(33, "meditate", "+1 spe, +1 spdef, +1spatk", "legendary", True)
    moves.append(newMove)
    newMove = move.Move(34, "destoyer's rights", "+1 spe, +1 atk, +1spatk", "legendary", True)
    moves.append(newMove)

    newMove = move.Move(40, "dragons breath", "100, 100%. This move lowers the spatk of the target.", "mythical", True)
    moves.append(newMove)
    newMove = move.Move(41, "Cosmic Catastrophy", "225, 100%. This move lowers all the users stats.", "mythical", True)
    moves.append(newMove)
    newMove = move.Move(42, "Earthshatter", "135, 100%. This move lowers the targets speed.", "mythical", True)
    moves.append(newMove)
    return moves

def initialize_cards(cards):
    newCard = card.Card(0,True,"cherry", "restores 25% hp when below half health", "common")
    cards.append(newCard)
    newCard = card.Card(1,True,"coins", "+3 coins", "common")
    cards.append(newCard)
    newCard = card.Card(2,True,"potion", "restores 20 hp when possible", "common")
    cards.append(newCard)
    newCard = card.Card(3,True,"caffeine up", "increases speed when below 25%", "common")
    cards.append(newCard)
    newCard = card.Card(4,True,"focus sash", "OHKO moves will leave you at 1hp", "common")
    cards.append(newCard)
    newCard = card.Card(5,True,"physical gem", "powers up a physical move", "common")
    cards.append(newCard)
    newCard = card.Card(6,True,"special gem", "powers up a special move", "common")
    cards.append(newCard)
    newCard = card.Card(7,True,"exp up", "grants some exp", "common")
    cards.append(newCard)

    newCard = card.Card(10,False,"exp charm", "grants more exp whenever granted", "rare")
    cards.append(newCard)
    newCard = card.Card(11,False,"luck charm", "feeling lucky?", "rare")
    cards.append(newCard)
    newCard = card.Card(12,True,"reset herb", "negates a stat drop", "rare")
    cards.append(newCard)
    newCard = card.Card(13,True,"copy herb", "copy a stat raise from the opponent", "rare")
    cards.append(newCard)
    newCard = card.Card(14,False,"physical scarf", "physical attacks do more", "rare")
    cards.append(newCard)
    newCard = card.Card(15,False,"special scarf", "special attacks do more", "rare")
    cards.append(newCard)

    newCard = card.Card(20,False,"intimidate", "lowers the opponents atk stat", "super rare")
    cards.append(newCard)
    newCard = card.Card(21,False,"aura", "lowers the opponents spatk stat", "super rare")
    cards.append(newCard)
    newCard = card.Card(22,False,"scope lens", "Raises crit chance", "super rare")
    cards.append(newCard)
    newCard = card.Card(23,False,"thorns", "attacker is damaged if they use a physical move", "super rare")
    cards.append(newCard)

    newCard = card.Card(30,False,"regeneration", "attacker is damaged if they use a physical move", "legendary")
    cards.append(newCard)
    newCard = card.Card(31,False,"recycle", "chance to gain an item about to be discarded", "legendary")
    cards.append(newCard)
    newCard = card.Card(32,False,"guarded", "First attack against the user is cut in half", "legendary")
    cards.append(newCard)
    newCard = card.Card(33,False,"foggy", "Grants higher evasion", "legendary")
    cards.append(newCard)

    newCard = card.Card(40,False,"divine attack", "Raises attack", "mythical")
    cards.append(newCard)
    newCard = card.Card(41,False,"cursed attack", "Raises special attack", "mythical")
    cards.append(newCard)
    newCard = card.Card(42,False,"quick feet", "gives all attacking move +1 priority", "mythical")
    cards.append(newCard)
    return cards